name: ci

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: "1.10.3.1053"
      - name: Check format
        run: |
          clojure -M:format check src
          clojure -M:format check test
